name: base
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10.6
  - mne=1.1.1
  - mne-features=0.2.1
  - ray-default
  - ray-core
  - ray-all
  - ray-dashboard
  - redis=3.5.3